[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = ["build/**"]

[build.environment]
  NODE_ENV = "production"
